org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true
org.gradle.warning.mode=all

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=26.3
enabled_platforms=fabric,neoforge

mod_id=chat_heads
archives_base_name=chat_heads
mod_version=1.2.8
maven_group=dzwdz

# common
java_version=25
cloth_config_version=26.3.158

# fabric
fabric_loader_version=0.19.5
fabric_loader_version_range=>=0.19.5
modmenu_version=21.0.0-beta.1

# neoforge
neoforge_version=26.3.0.1-beta

# publishing
modrinth_id=Wb5oqrBJ
curseforge_id=407206
fabric_game_version_range=>=26.3
fabric_game_versions=26.3
neoforge_game_version_range=[26.3, )
neoforge_game_versions=26.3
optional_modrinth_dependencies=9s6osm5g
optional_curseforge_dependencies=cloth-config
